# Generated by Django 4.2.7 on 2023-11-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # If this current migration has any dependencies on other migrations then it'll show here like 
    # suppose 0001 has a dependency on 0001.** something like that then it'll show ('home',0001.**)
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
