# Generated by Django 4.2.7 on 2023-11-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_phone_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_num',
            new_name='phone',
        ),
    ]
