# Generated by Django 4.2.7 on 2023-11-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_description',
            new_name='recipe_description',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_name',
            new_name='recipe_name',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_image',
        ),
        migrations.AddField(
            model_name='receipe',
            name='recipe_image',
            field=models.ImageField(default='image.png', upload_to='recipe'),
        ),
    ]
