# Generated by Django 4.2.7 on 2023-11-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_rename_receipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='recipe/image.jpg', upload_to='recipe'),
        ),
    ]
